### ISSUE TITLE
Unknown bugs

### ISSUE THREAD

**Issue by darshjain** [fkie-cad/socbed#96] opened 2024-10-30 00:43 UTC
**Describe the bug**
While running 
$ ./tools/build_vms

I recieve two errors 
![image](https://github.com/user-attachments/assets/440b3871-35cb-4cd5-aa6a-75ae1ca11ad5)

and 

![image](https://github.com/user-attachments/assets/b8d26d9b-8fc8-4741-ab62-b5844d8ac6b7)

**Host system (please complete the following information):**
 - OS & version: [e.g. Ubuntu 22.04]
 - VirtualBox version: [7.0]

**Comment by Maspital** [comment] 2024-10-30 06:54
I am unable to reproduce this both on our runner and locally.
The first image seems to suggest an older version of Python - is your host running at least Python3.9?
What's the output if you run `pip freeze | grep ansible`?

**Comment by darshjain** [comment] 2024-10-30 14:48
Python 3.12.3


Ouptut -
ansible==10.5.0
ansible-core==2.17.5

**Comment by darshjain** [comment] 2024-10-30 19:36
Just a follow up, I happened to notice while tinkering with post_install for log_server, that apt update doesn't work : it is not able to establish its Internet Connection. To confirm this, I increased the timeout to 10 mins and ssh'ed into the server. It is not able to ping to any online resource. This is a important issue to address as well.

**Comment by Maspital** [comment] 2024-10-31 08:48
The problem, as indicated by your screenshots, is the version of `ansible-core` you are running. This is caused by the Ansible version you have installed (`10.5.0`) not matching the one listed in `requirements.txt`.  Did you install them with `pip install -r requirements.txt` inside a clean virtual environment?

**Comment by Maspital** [comment] 2024-11-04 08:02
Closing, feel free to re-open if the issue persists.

**Closed by Maspital** 2024-11-04 08:02 UTC
Labels: bug
