### ISSUE TITLE
Logging and NTP system tests are unstable

### ISSUE THREAD

**Issue by ru37z** [fkie-cad/socbed#23] opened 2021-12-10 09:39 UTC
**Describe the bug**
The logging and NTP (active and passive) system tests often fail even though logging and NTP seem to work properly. They are therefore currently labeled as "unstable" and not included in the nightly build.

**To Reproduce**
`tox -- -m "unstable"`

**Expected behavior**
All three system tests should always pass and of course check if logging and NTP work as desired.

**Comment by Maspital** [comment] 2022-05-09 08:15
Regarding logging systests:
While this test almost always succeeds locally, it sometimes fails on our runner. Changing the used search keyword within the test from `timestamp` to `@timestamp` seems to improve stability; coupled with the increased retry count of our systests this should elevate the reliability of the logging tests to a point where we can re-enable them in our pipeline.

Regarding NPT systests:
These tests exhibit strange behavior both locally and on our runner. I suspect that these issues might be caused by more general problems related to our domain, and suggest that we look into this again when we switch from Linux- to Windows-Domain.

Closing since all concerns have been addressed for now, we can re-open this once/if we start working on the Windows-Domain.

**Closed by Maspital** 2022-05-09 08:15 UTC
Labels: bug
